In [1]:
import numpy as np

In [16]:
W_COL = np.matrix('0, 0, 3, 4, 4; 5, 6, 0, 0, 0; 0, 0, 6, 5, 5')
X_COL = np.matrix('0, 0, 6; 4, 3, 0; 0, 0, 3; 5, 6, 0; 5, 6, 0')

In [17]:
W_COL

matrix([[0, 0, 3, 4, 4],
        [5, 6, 0, 0, 0],
        [0, 0, 6, 5, 5]])

In [18]:
np.min(W_COL.shape)

3

In [19]:
X_COL

matrix([[0, 0, 6],
        [4, 3, 0],
        [0, 0, 3],
        [5, 6, 0],
        [5, 6, 0]])

In [20]:
np.min(X_COL.shape)

3

In [21]:
def squarify(M):
    (a,b)=M.shape 
    if a>b:
        padding=((0,0),(0,a-b))
    else:
        padding=((0,b-a),(0,0))
    return np.pad(M,padding,mode='constant')
def old_shape(M):
    return np.min(M.shape)
def strassen_algorithm(x, y):
    """Return nxn Matrix multiplication."""
    if x.size == 1 or y.size == 1:
        return x * y
    n = x.shape[0]
    if n % 2 == 1:
        x = np.pad(x, (0, 1), mode='constant')
        y = np.pad(y, (0, 1), mode='constant')
    m = int(np.ceil(n / 2))
    a = x[: m, : m]
    b = x[: m, m:]
    c = x[m:, : m]
    d = x[m:, m:]
    e = y[: m, : m]
    f = y[: m, m:]
    g = y[m:, : m]
    h = y[m:, m:]
    p1 = strassen_algorithm(a, f - h)
    p2 = strassen_algorithm(a + b, h)
    p3 = strassen_algorithm(c + d, e)
    p4 = strassen_algorithm(d, g - e)
    p5 = strassen_algorithm(a + d, e + h)
    p6 = strassen_algorithm(b - d, g + h)
    p7 = strassen_algorithm(a - c, e + f)
    result = np.zeros((2 * m, 2 * m), dtype=np.int32)
    result[: m, : m] = p5 + p4 - p2 + p6
    result[: m, m:] = p1 + p2
    result[m:, : m] = p3 + p4
    result[m:, m:] = p1 + p5 - p3 - p7
    return result[: n, : n]

In [28]:
# print(strassen_algorithm(squarify(W_COL), squarify(X_COL)))
print(np.array(strassen_algorithm(squarify(W_COL), squarify(X_COL))[:old_shape(W_COL), :old_shape(X_COL)]))

[[40 48  9]
 [24 18 30]
 [50 60 18]]


In [31]:
(squarify(W_COL) @ squarify(X_COL))[:old_shape(W_COL), :old_shape(X_COL)]

array([[40, 48,  9],
       [24, 18, 30],
       [50, 60, 18]])